spring:
  application:
    name: marujang
  output:
    ansi:
      enabled: always
  config:
    import: optional:application-secret.yml
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/marujang}
    username: ${DB_USERNAME:marujang}
    password: ${DB_PASSWORD:marujang}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
